# Copyright (c) 2018 Numforge SARL
# Distributed under the Apache v2 License (license terms are at https://www.apache.org/licenses/LICENSE-2.0).

import ./generated/[clblast_c, clblast_netlib_c]
# Note half conversion table cannot be autogenerated
# So we do not expose the hal precision (even though we expose proc that can use it)

export clblast_c, clblast_netlib_c